### PR TITLE
[WIP] PSR-6 Cache implementation of state storage

### PR DESCRIPTION
**Pull request by neeckeloo**

### CODE REVIEW

**Comment by lcf** [comment]
tests fail, also @neeckeloo could you first file an issue for each pull request and explain reasoning and the kind of issues you've been having so that we can discuss and choose the best solution

**Comment by neeckeloo** [comment]
You can see #25 to understand why this PR build failed.

Do not you think you've closed the pull request a little prematurely? IMO, a pull request can aim to start a discussion like an issue.

I proposed to implement a state storage based on PSR-6 Cache interfaces to improve flexibility. Currently, the package allow only to use APC to store metrics.

**Comment by neeckeloo** [comment]
No interest in this proposal? If not, I will have to create a small repository with this state storage implementation.

**Comment by lcf** [comment]
@neeckeloo could you first file an issue for each pull request and explain reasoning and the kind of issues you've been having so that we can discuss and choose the best solution.

**Pull request closed without merging**
