### PR TITLE
Requiring at least PHP 5.6 as minimum installed PHP version

### PR DESCRIPTION
**Pull request by neeckeloo**

### CODE REVIEW

**Comment by lcf** [comment]
@neeckeloo I do not follow. Why?

**Comment by lcf** [comment]
@neeckeloo could you first file an issue for each pull request and explain reasoning and the kind of issues you've been having so that we can discuss and choose the best solution

**Comment by neeckeloo** [comment]
I suggest to require PHP 5.6 as minimum PHP version because PHP 5.5 is now EOL and older versions (PHP 5.3 and 5.4) are not supported since a while.

http://php.net/supported-versions.php

**Comment by lcf** [comment]
@neeckeloo You are not required to use PHP 5.3 or PHP 5.4 to use Phystrix. It works with newer PHP versions as well.

**Pull request closed without merging**
